version: '3.1'

services:
  form_app:
    build: .
    image: form_app
    ports:
      - "5000:5000"
    volumes:
      - ./form_app/src:/var/www/
    env_file: .env
  mongodb:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    env_file: .env
